# Generated by Django 6.0 on 2025-12-16 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('folder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('google_folder_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='googleDriveApp.drivefolder')),
            ],
        ),
        migrations.CreateModel(
            name='DriveFile',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('google_file_id', models.CharField(max_length=255, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('web_view_link', models.URLField(blank=True, null=True)),
                ('web_content_link', models.URLField(blank=True, null=True)),
                ('thumbnail_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googleDriveApp.drivefolder')),
            ],
        ),
    ]
